[package]
name = "dygma_focus"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Wilding <mbwilding@gmail.com>"]

[dependencies]
anyhow = "1.0"
custom_macros = { path = "../custom_macros" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serialport = "4.3"
tracing = "0.1"
