name: Publish Crates

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Crates
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install Packages"
        run: sudo apt-get install -y libudev-dev

      - name: "Rust Toolchain"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: "Publish Crates"
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
